#Faça um programa que leia um número inteiro qualquer e mostre na tela sua tabuada

num1=int(input('Type an integer number: '))
print('-'*12)
print('{} x 1 = {:2}'.format(num1, num1*1))
print('{} x 2 = {:2}'.format(num1, num1*2))
print('{} x 3 = {:2}'.format(num1, num1*3))
print('{} x 4 = {:2}'.format(num1, num1*4))
print('{} x 5 = {:2}'.format(num1, num1*5))
print('{} x 6 = {:2}'.format(num1, num1*6))
print('{} x 7 = {:2}'.format(num1, num1*7))
print('{} x 8 = {:2}'.format(num1, num1*8))
print('{} x 9 = {:2}'.format(num1, num1*9))
print('{} x 10 = {:2}'.format(num1, num1*10))
print('-'*12)